#
#org.gradle.caching=true
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.problems=warn

org.gradle.parallel=true
org.gradle.daemon=true

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

org.gradle.incremental=true

systemProp.http.keepAlive=true
systemProp.http.connectionTimeout=60000
systemProp.http.socketTimeout=60000
systemProp.https.keepAlive=true
systemProp.https.connectionTimeout=60000
systemProp.https.socketTimeout=60000

android.useAndroidX=true
android.enableBuildCache=true
android.enableR8.fullMode=true
android.nonTransitiveRClass=true

kotlin.incremental=true
kotlin.incremental.android=true
kotlin.incremental.java=true
kotlin.incremental.useClasspathSnapshot=true
kotlin.incremental.usePreciseJavaTracking=true

org.gradle.internal.http.connectionTimeout=60000
org.gradle.internal.http.socketTimeout=60000
